/**
 * Sample text for the demo. Every identifier here is SYNTHETIC — the Aadhaar
 * and GSTIN values were generated by computing valid check digits over
 * arbitrary digit strings, exactly as the test fixtures are. No real person's
 * identifiers appear anywhere in this repository.
 */
export const SAMPLE_TEXT = `Support ticket #48213 — vendor onboarding, escalated

Caller: Ravi K., verified over the phone on +91 98765 43210.
He also left an alternate number, 7012345678, but it went to voicemail.

Documents he emailed to ravi.k@example.co.in for the KYC file:
  - Aadhaar 2345 6789 0124
  - PAN ABCPE1234F
  - Second Aadhaar on the joint application: 9876 5432 1013
  - GSTIN for the firm: 27ABCDE1234F1Z0
  - Settlement account IFSC HDFC0001234, UPI ravi.k@okhdfcbank
  - Delivery address ends 560103, vehicle at the gate is KA05MJ2023

The Hindi-language form has the same Aadhaar typed in Devanagari:
आधार संख्या २३४५ ६७८९ ०१२४ — दर्ज दिनांक ०८/०९/२०२६

Internal note: invoice 412356789046 was raised against this account, and
the warehouse bay is 400072. Neither is personal data.`;
